language: go
go:
  - 1.5.2
  - 1.5.3
sudo: false

install:
    - go get -u github.com/golang/lint/golint
    - go get -u github.com/spf13/cobra
    - go get -u github.com/spf13/viper
    - go get -u github.com/google/go-github/github
    - go get -u golang.org/x/oauth2

script:
    - test -z "$(golint reviewer)"
    - golint reviewer
    - go test github.com/gophergala2016/reviewer/reviewer
    - go vet
